local config = turkoid.config
config.healingdebuffs = {
	["reduced"] = {
		"Aimed Shot",
		"Furious Attacks",
		"Mind Trauma",
		"Mortal Strike",
		"Wound Poison",
		"Touch of the Forgotten",
		"Arcing Smash",
		"Curse of the Bleeding Hollow",
		"Curse of the Deadwood",
		"Brood Affliction: Green",
		"Dark Touched",
		"Dark Volley",
		"Deathblow",
		"Demolish",
		"Ebon Poison",
		"Filet",
		"Gehennas' Curse",
		"Hex of Weakness",
		"Magma-Thrower's Curse",
		"Mortal Cleave",
		"Mortal Wound",
		"Necrotic Poison",
		"Necrotic Strike",
		"Nether Portal",
		"Ray of Pain",
		"Shadow Spike",
		"Shroud of Darkness",
		"Solar Strike",
		"Soul Strike",
		"Veil of Shadow",
		"Wretched Strike",
	},
	["prevented"] = {	
		"Aura of Suffering",
		"Darkness",
		"Enfeeble",
		"Necrotic Aura",
	},
}