local _, ns = ...
local oUF = ns.oUF or oUF
turkoid = CreateFrame("frame")
turkoid.config = {
	["roman"] = {"I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X", "XI", "XII", "XIII", "XIV", "XV", "XVI", "XVII", "XVIII", "XIX", "XX"},	
	["classification"] = {
		worldboss = "Boss",
		rareelite = "Rare Elite",
		elite = "Elite",
		rare = "Rare",
		normal = "",
		trivial = "",
	},
	["druidforms"] = {
		["Cat Form"] = "Cat",
		["Bear Form"] = "Bear",
		["Dire Bear Form"] = "Bear",
		["Travel Form"] = "Travel",
		["Aquatic Form"] = "Aquatic",
		["Flight Form"] = "Flight",
		["Swift Flight Form"] = "Flight",
		["Moonkin Form"] = "Moonkin",
		["Tree of Life"] = "Tree",
	},
	["background"] = {
		["texture"] = "Interface\\Addons\\MyMedia\\whiteborder", --"Interface\\ChatFrame\\ChatFrameBackground",
		["tile"] = true,
		["tilesize"] = 16,
		["insets"] = {
			["left"] = 0, 
			["right"] = 0, 
			["top"] = 0, 
			["bottom"] = 0,
		},
		["alpha"] = 0.7,
	},
	["border"] = {
		["texture"] = "Interface\\Addons\\MyMedia\\whiteborder",
		["size"] = 1,
	},	
	["statusbar"] = "Interface\\AddOns\\MyMedia\\Smoothv2",
	["font"] = {
		["name"] = "Interface\\AddOns\\MyMedia\\ABF.ttf", --'Interface\\AddOns\\Skada\\fonts\\Accidental_Presidency'
		["size"] = 14,
		["color"] = {r = 1, g = 1, b = 1},
	},
	["combopoints"] = "Interface\\AddOns\\MyMedia\\cpoint",
	["debuffhighlight"] = {
		["texture"] = "Interface\\AddOns\\MyMedia\\debuffHighlight",
		["alpha"] = .75,
	},
	["textoffset"] = 4,
	["insideRangeAlpha"] = 1,
	["outsideRangeAlpha"] = 0.4,
	["player"] = {
		["height"] = 66,
		["width"] = 310,
		["position"] = {
			["selfAnchor"] = "TOPRIGHT",
			["target"] = "ui",
			["targetAnchor"] = "TOP",
			["xOffset"] = -1,
			["yOffset"] = -825,
		},
		["healthbar"] = {
			["height"] = 36, 
		},
		["powerbar"] = {
			["height"] = 16,
		},
		["druidbar"] = {
			["height"] = 12,
			["fontsize"] = 12,
		},
		["experience"] = {
			["height"] = 12,
			["fontsize"] = 12,
		},
		["powerspark"] = true,
		["leadericon"] = true,
		["assistanticon"] = true,
		["roleicon"] = true,
		["masterlooticon"] = true,
		["combaticon"] = true,
		["raidicon"] = true,
		["debuffhighlight"] = true,
		["buffs"] = {
			["size"] = 30,
			["cols"] = 19,
			["rows"] = 2,
			["anchorpoint"] = "TOPRIGHT",
			["parentanchor"] = "TOPRIGHT",
			["initialanchor"] = "TOPRIGHT",
			["xoffset"] = -9,
			["yoffset"] = -9,			
			["growthx"] = "LEFT",
			["growthy"] = "DOWN",
			["paddingx"] = 9, 
			["paddingy"] = 20, 
		},
		["debuffs"] = {
			["size"] = 30,
			["cols"] = 19,
			["rows"] = 2,
			["anchorpoint"] = "TOPRIGHT",
			["parentanchor"] = "TOPRIGHT",
			["initialanchor"] = "TOPRIGHT",
			["xoffset"] = -9,
			["yoffset"] = -114,
			["growthx"] = "LEFT",
			["growthy"] = "DOWN",
			["paddingx"] = 9, 
			["paddingy"] = 20, 
		},
		["texts"] = {
			["name"] = "[name] [flags]",
			["unitinfo"] = "[classification] [diffcolor][level]|r [classcolor][classbase]|r [druidform] [SmartRace]",
			["health"] = "[SmartFullHP]",
			["power"] = "[SmartPP]",
			["druidpower"] = "[druidcurpp]/[druidmaxpp]",
			["experience"] = "[curxp]/[maxxp]",
		},
	},
	["target"] = {
		["height"] = 66,
		["width"] = 310,
		["position"] = {
			["selfAnchor"] = "TOPLEFT",
			["target"] = "ui",
			["targetAnchor"] = "TOP",
			["xOffset"] = 1,
			["yOffset"] = -825,
		},
		["healthbar"] = {
			["height"] = 36,
		},
		["powerbar"] = {
			["height"] = 16,
		},
		["combopoints"] = true,
		["leadericon"] = true,
		["roleicon"] = true,
		["masterlooticon"] = true,
		["raidicon"] = true,
		["debuffhighlight"] = true,
		["rangecheck"] = true,
		["buffs"] = {
			["size"] = 16.3,
			["cols"] = 19,
			["rows"] = 1,
			["anchorpoint"] = "TOPLEFT",
			["selfanchor"] = "BOTTOMLEFT",
			["initialanchor"] = "TOPLEFT",
			["growthx"] = "RIGHT",
			["growthy"] = "DOWN",
		},
		["debuffs"] = {
			["size"] = 23.8,
			["cols"] = 13,
			["rows"] = 3,
			["anchorpoint"] = "BOTTOMLEFT",
			["selfanchor"] = "TOPLEFT",
			["initialanchor"] = "BOTTOMLEFT",
			["growthx"] = "RIGHT",
			["growthy"] = "UP",
		},
		["texts"] = {
			["name"] = "[name] [flags]",
			["unitinfo"] = "[classification] [diffcolor][level]|r [classcolor][classbase]|r [druidform] [SmartRace]",
			["health"] = "[SmartFullHP]",
			["power"] = "[SmartPP]",
		},
	},
	["targettarget"] = {
		["height"] = 38,
		["width"] = 238,
		["position"] = {
			["selfAnchor"] = "TOPLEFT",
			["target"] = "target",
			["targetAnchor"] = "TOPRIGHT",
			["xOffset"] = 2,
			["yOffset"] = 0,
		},
		["healthbar"] = {
			["height"] = 36,
		},
		["raidicon"] = true,
		["debuffs"] = {
			["size"] = 23.8,
			["cols"] = 10,
			["rows"] = 3,
			["anchorpoint"] = "BOTTOMLEFT",
			["selfanchor"] = "TOPLEFT",
			["initialanchor"] = "BOTTOMLEFT",
			["growthx"] = "RIGHT",
			["growthy"] = "UP",
		},
		["texts"] = {
			["name"] = "[name]",
			["health"] = "[SmartPercHP]",

		},
	},
	["pet"] = {
		["height"] = 66,
		["width"] = 238,
		["position"] = {
			["selfAnchor"] = "TOPRIGHT",
			["target"] = "player",
			["targetAnchor"] = "TOPLEFT",
			["xOffset"] = -2,
			["yOffset"] = 0,
		},
		["healthbar"] = {
			["height"] = 36,
		},
		["powerbar"] = {
			["height"] = 16,
		},
		["castbar"] = {
			["height"] = 12,
			["fontsize"] = 12,
			["hidetext"] = true,
		},
		["raidicon"] = true,
		["debuffhighlight"] = true,
		["rangecheck"] = true,
		["buffs"] = {
			["size"] = 16.3,
			["cols"] = 7,
			["rows"] = 1,
			["anchorpoint"] = "TOPLEFT",
			["selfanchor"] = "BOTTOMLEFT",
			["initialanchor"] = "TOPLEFT",
			["growthx"] = "RIGHT",
			["growthy"] = "DOWN",
		},
		["debuffs"] = {
			["size"] = 16.3,
			["cols"] = 7,
			["rows"] = 1,
			["anchorpoint"] = "TOPRIGHT",
			["selfanchor"] = "BOTTOMRIGHT",
			["initialanchor"] = "TOPRIGHT",
			["growthx"] = "LEFT",
			["growthy"] = "DOWN",
		},
		["texts"] = {
			["name"] = "[name]",
			["unitinfo"] = "[classification] [diffcolor][level]|r [classcolor][classbase]|r [druidform] [SmartRace]",
			["health"] = "[SmartPercHP]",
			["power"] = "[SmartPP]",
		},
	},
	["party"] = {
		["height"] = 66,
		["width"] = 237,
		["position"] = {
			["selfAnchor"] = "TOPLEFT",
			["target"] = "ui",
			["targetAnchor"] = "TOP",
			["xOffset"] = 313,
			["yOffset"] = -910,
			["spacing"] = 6.82,
			["direction"] = "DOWN",
		},
		["healthbar"] = {
			["height"] = 36,
		},
		["powerbar"] = {
			["height"] = 16,
		},
		["castbar"] = {
			["height"] = 12,
			["fontsize"] = 12,
		},
		["leadericon"] = true,		
		["roleicon"] = true,
		["masterlooticon"] = true,
		["raidicon"] = true,
		["debuffhighlight"] = true,
		["rangecheck"] = true,
		["buffs"] = {
			["size"] = 17,
			["cols"] = 14,
			["rows"] = 1,
			["anchorpoint"] = "TOPLEFT",
			["selfanchor"] = "TOPRIGHT",
			["initialanchor"] = "TOPLEFT",
			["growthx"] = "RIGHT",
			["growthy"] = "DOWN",
		},
		["debuffs"] = {
			["size"] = 17,
			["cols"] = 14,
			["rows"] = 1,
			["anchorpoint"] = "TOPLEFT",
			["selfanchor"] = "TOPRIGHT",
			["initialanchor"] = "TOPLEFT",
			["yoffset"] = -17,
			["growthx"] = "RIGHT",
			["growthy"] = "UP",
		},
		["texts"] = {
			["name"] = "[name] [flags]",
			["unitinfo"] = "[classification] [diffcolor][level]|r [classcolor][classbase]|r [druidform] [SmartRace]",
			["health"] = "[SmartFullHP]",
			["power"] = "[SmartPP]",
		},
	},
	["partytarget"] = {
		["height"] = 30,
		["width"] = 238,
		["healthbar"] = {
			["height"] = 28,
		},
		["raidicon"] = true,
		["texts"] = {
			["name"] = "[name]",
			["health"] = "[SmartPercHP]",
		},
	},
	["partypet"] = {
		["height"] = 30,
		["width"] = 165,
		["healthbar"] = {
			["height"] = 28,
		},
		["debuffhighlight"] = true,
		["rangecheck"] = true,
		["texts"] = {
			["name"] = "[name]",
			["health"] = "[SmartPercHP]",
		},
	},
	["focus"] = {
		["height"] = 66,
		["width"] = 250,
		["position"] = {
			["selfAnchor"] = "TOP",
			["target"] = "ui",
			["targetAnchor"] = "TOP",
			["xOffset"] = 0,
			["yOffset"] = -2,
		},
		["healthbar"] = {
			["height"] = 36,
		},
		["powerbar"] = {
			["height"] = 16,
		},
		["raidicon"] = true,
		["rangecheck"] = true,
		["buffs"] = {
			["size"] = 22,
			["cols"] = 4,
			["rows"] = 3,
			["anchorpoint"] = "TOPRIGHT",
			["selfanchor"] = "TOPLEFT",
			["initialanchor"] = "TOPRIGHT",
			["growthx"] = "LEFT",
			["growthy"] = "DOWN",
		},
		["debuffs"] = {
			["size"] = 22,
			["cols"] = 3,
			["rows"] = 4,
			["anchorpoint"] = "TOPLEFT",
			["selfanchor"] = "TOPRIGHT",
			["initialanchor"] = "TOPLEFT",
			["growthx"] = "RIGHT",
			["growthy"] = "DOWN",
		},
		["texts"] = {
			["name"] = "[name]",
			["unitinfo"] = "[classification] [diffcolor][level]|r [classcolor][classbase]|r [druidform] [SmartRace]",
			["health"] = "[SmartFullHP]",
			["power"] = "[SmartPP]",
		},
	},	
	["focustarget"] = {
		["height"] = 30,
		["width"] = 250,
		["position"] = {
			["selfAnchor"] = "TOP",
			["target"] = "focus",
			["targetAnchor"] = "BOTTOM",
			["xOffset"] = 0,
			["yOffset"] = -2,
		},
		["healthbar"] = {
			["height"] = 28,
		},
		["texts"] = {
			["name"] = "[name]",
			["health"] = "[SmartPercHP]",
		},
	},
	["boss"] = {
		["height"] = 40,
		["width"] = 250,
		["position"] = {
			["selfAnchor"] = "TOPLEFT",
			["target"] = "ui",
			["targetAnchor"] = "TOPLEFT",
			["xOffset"] = 5,
			["yOffset"] = -350,
		},
		["healthbar"] = {
			["height"] = 28,
		},
		["powerbar"] = {
			["height"] = 10,
		},
		["texts"] = {
			["name"] = "[name]",
			["health"] = "[SmartFullHP]",
			["power"] = "[SmartPP]",
		},
	},
}

if UnitName("player") == "Yattay" then
	turkoid.config.player.texts.health = "[SmartFullMissingHP]"
	turkoid.config.target.texts.health = "[SmartFullMissingHP]"
	turkoid.config.party.texts.health = "[SmartFullMissingHP]"
	
	--turkoid.config.player.position.yOffset = -800
	--turkoid.config.target.position.yOffset = -800
end